spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.johnyu.domain
server:
  port: 3200